### PR TITLE
For PRs, post the transfer.sh URL(s) to the PR as review comment

### PR DESCRIPTION
**Pull request by dirkhh**
This is a fun one, I think.
When people submit PRs, often they want others to be able to test this on platforms they don't have access to. But of course PRs only push their binaries to transfer.sh and you need to dig through that output in order to figure out where to find those binaries.
With this change, a comment is posted to the PR that points to those binaries. For example see here: https://github.com/dirkhh/testrepo/pull/1
I think that's a neat extension of what uploadtool does :-)

### CODE REVIEW

**Comment by dirkhh** [comment]
OK, pushed new version that contains the changes @probonopd requested on IRC.
See the last entry on https://raw.githubusercontent.com/dirkhh/uploadtool/master/upload.sh

**Comment by probonopd** [comment]
Very, very useful. Thank you so much @dirkhh

**Comment by probonopd** [comment]
Shouldn't it have commented https://github.com/AppImage/AppImageKit/pull/534? Or do we need to set up something in the repo differently?

**Comment by probonopd** [comment]
@dirkhh there seem to be further issues, as it didn't paste the URLs here: https://github.com/AppImage/AppImageKit/pull/528#pullrequestreview-77643079

**Comment by dirkhh** [comment]
There are a couple of problems that I see.
If there are no artifacts at all (as in https://github.com/AppImage/AppImageKit/pull/528#pullrequestreview-77643079) it I think upload.sh should simply bail out right away - no point in creating the release entry if there are no artifacts to upload, right?
The other case is more surprising... the error is 
```
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}
```
which I have seen happen if you end up with "" as your message (which is what would happen because of my stupid typo). The easiest way to debug this is to enable "set -x" in the "PR" conditional in upload.sh here https://github.com/probonopd/uploadtool/blob/master/upload.sh#L34-L54
I'll send you two small PRs with an idea for making this more robust.

**Comment by probonopd** [comment]
Thanks for checking. Yes, that's surprising given that artifacts generally are uploaded to https://github.com/AppImage/AppImageKit/releases fine.

**Comment by probonopd** [comment]
Nope, the review comments still don't appear to be working:
https://github.com/AppImage/AppImageKit/pull/535#pullrequestreview-77651904

**Pull request merged**
