### PR TITLE
Add AppVeyor support

### PR DESCRIPTION
**Pull request by wojnilowicz**

### CODE REVIEW

**Comment by probonopd** [comment]
Thank you @wojnilowicz. Have you successfully tested it on both systems? (I am not using AppVeyor myself.)

**Comment by wojnilowicz** [comment]
> Thank you @wojnilowicz. Have you successfully tested it on both systems? (I am not using AppVeyor myself.)

Yes. You can see results [here](https://github.com/wojnilowicz/kmymoneynext/releases)

**Comment by probonopd** [comment]
Is there any way to have one continuous release instead of four?

**Comment by wojnilowicz** [comment]
Will it be merged?

**Comment by probonopd** [comment]
For now I am a bit hesitant to merge since I do not have the time to test it properly and we have many Travis CI users who critically rely on `uploadtool`. It would be good if we could have some more users (also Travis CI users) to test and confirm that it does not break anything. (I'm just being extra cautious here.)

**Pull request closed without merging**
