### PR TITLE
Collate artifacts

### PR DESCRIPTION
**Pull request by dirkhh**
With this we create only one comment that combines the various artifacts.
This still creates multiple comments for the different architectures.
Combining those turned out to be a bit harder than I thought

### CODE REVIEW

**Comment by probonopd** [comment]
Thank you very much.

**Comment by dirkhh** [comment]
Funny how I appear to be the only person working on this cool tool right now :-)

**Comment by dirkhh** [comment]
(this may come across like a dig or complaint... not at all... just an observation that somehow amuses me)

**Comment by probonopd** [comment]
If it is not possible to collate multiple architectures, then maybe just post the first one.

**Comment by probonopd** [comment]
> Funny how I appear to be the only person working on this cool tool right now :-)

Well, /me considered this little hack to be "feature complete" on Dec 3, 2016 - until you showed me it's true potential ;-)

**Comment by dirkhh** [comment]
I didn't say it was not possible... I said it was harder than I thought and I wanted to submit this in the meantime...
What's bothering me, though, is that I still get a "Bad credentials" response on PRs. It works in all of my tests, but something is still not going right on _real_ PRs. And I can't figure out what. Obviously the credentials are wrong, but how's that possible?

**Comment by dirkhh** [comment]
My big challenge is... how do I run something after ALL the builds are completed?
Because I can't seem to figure out how to edit a comment (so that I could incrementally add artifacts as they are created), nor have I figured out how to delete a posted one (without adding noise about "dismissed reviews").

**Comment by probonopd** [comment]
If I understand correctly how Travis CI works, PRs intentionally don't get secure variables such as `GITHUB_TOKEN` exported (at least not with their real value) because that might be a security issue.

**Comment by probonopd** [comment]
> My big challenge is... how do I run something after ALL the builds are completed?

I think @TheAssassin recently said something about a new Travis CI feature called "build cascades" or something like that

**Comment by dirkhh** [comment]
they have "build stages" as a beta feature I just found. That's what can do this.
But I need to read up on PRs and secure variables

**Comment by dirkhh** [comment]
Duh. What I'm trying to do is explicitly prevented unless the branch you are merging is in the same repo that you are targeting with the PR. Which is of course exactly how I always tested this, but it is NOT how normal users would submit PRs. So I need to re-architect this and check if there's a different way that we can post those addresses to the PR page... as I mentioned in the original rationale - the goal is to make it easier for others to test the impact of a PR by having readily available binaries...

**Comment by probonopd** [comment]
Yes, he had mentioned "build stages".

**Pull request merged**
