### PR TITLE
Add code to be more verbose when review comment fails

### PR DESCRIPTION
**Pull request by dirkhh**
This is untested as I am running out of time here - the idea should be obvious, but I'm worried if my quotation marks are correct. So please test this against a PR where you have seen upload.sh fail to post a comment...

### CODE REVIEW

**Comment by probonopd** [comment]
@TheAssassin @dirkhh do you have a good idea how to 

> test this against a PR where you have seen upload.sh fail to post a comment

**Comment by dirkhh** [comment]
Re-trigger the build of one where it happened, I think PR #534 on AppImage for example.

**Comment by probonopd** [comment]
Merged and build re-triggered for https://github.com/AppImage/AppImageKit/pull/534

**Comment by dirkhh** [comment]
Did the re-triggered build show anything useful? I didn't see the output of that build - but the PR doesn't appear to have review comments inserted from upload.sh, so clearly it's not working correctly, yet.

**Comment by probonopd** [comment]
I think Travis CI had hiccups today which may explain that some builds didn't go as expected.

**Pull request merged**
